apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eje314fgj-python
  janus-idp.io/tekton: eje314fgj-python
  backstage.io/kubernetes-id: eje314fgj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eje314fgj-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
