apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eje314fgj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eje314fgj-python 
  name: eje314fgj-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eje314fgj-python 
